WIP

diff --git a/.github/workflows/config.yml b/.github/workflows/config.yml
--- a/.github/workflows/config.yml
+++ b/.github/workflows/config.yml
@@ -11,69 +11,109 @@ on:
     types: [ published ]
 
 jobs:
-  build:
+  # build:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - name: Check out repository
+  #     uses: actions/checkout@v3
+  #     with:
+  #       fetch-depth: 0
+  #   - name: Setup node
+  #     uses: actions/setup-node@v3
+  #     with:
+  #       node-version: 16
+  #   - name: Print tooling versions
+  #     run: |
+  #       node --version
+  #       npm --version
+  #       docker --version
+  #       python --version
+  #   - name: Run npm ci
+  #     run: npm ci
+  #   - run: npm run build
+  #   - name: Upload build artifact
+  #     uses: actions/upload-artifact@v3
+  #     with:
+  #       name: build
+  #       path: ./dist
+
+  # test:
+  #   needs: build
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - name: Check out repository
+  #     uses: actions/checkout@v3
+  #   - name: Setup node
+  #     uses: actions/setup-node@v3
+  #     with:
+  #       node-version: 16
+  #   - name: Download build artifact
+  #     uses: actions/download-artifact@v3
+  #     with:
+  #       name: build
+  #       path: ./dist
+  #   - run: npm install --no-save tap-xunit
+  #   - run: mkdir -p _out/unit _out/e2e
+  #   - run: npm test -- --timeout=1m
+
+  release-to-staging:
+    if: github.event_name == 'pull_request' && github.head_ref == 'master'
     runs-on: ubuntu-latest
     steps:
-    - name: Check out repository
-      uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
-    - name: Setup node
-      uses: actions/setup-node@v3
-      with:
-        node-version: 16
-    - name: Print tooling versions
-      run: |
-        node --version
-        npm --version
-        docker --version
-        python --version
-    - name: Run npm ci
-      run: npm ci
-    - run: npm run build
-    - name: Upload build artifact
-      uses: actions/upload-artifact@v3
-      with:
-        name: build
-        path: ./dist
-
-  test:
-    needs: build
-    runs-on: ubuntu-latest
-    steps:
-    - name: Check out repository
-      uses: actions/checkout@v3
-    - name: Setup node
-      uses: actions/setup-node@v3
-      with:
-        node-version: 16
-    - name: Download build artifact
-      uses: actions/download-artifact@v3
-      with:
-        name: build
-        path: ./dist
-    - run: npm install --no-save tap-xunit
-    - run: mkdir -p _out/unit _out/e2e
-    - run: npm test -- --timeout=1m
-
-
-  version-bump:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout Code
+      - name: Check out repository
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
 
+      - name: Extract PR title
+        id: extract_title
+        run: |
+          TITLE="${{ github.event.pull_request.title }}"
+          echo "::set-output name=pr_title::$TITLE"
+
+      - name: Determine Version Increment
+        id: version_increment
+        run: |
+          TITLE="${{ steps.extract_title.outputs.pr_title }}"
+          
+          if [[ $TITLE == Patch* ]]; then
+            echo "::set-output name=increment::patch"
+          elif [[ $TITLE == Minor* ]]; then
+            echo "::set-output name=increment::minor"
+          elif [[ $TITLE == Major* ]]; then
+            echo "::set-output name=increment::major"
+          else
+            echo "Invalid PR title. Exiting."
+            exit 1
+          fi
+
       - uses: rickstaa/action-get-semver@v1
         id: get_semver
         with:
-          bump_level: "minor"
+          bump_level: "${{ steps.version_increment.outputs.increment }}"
+
       - name: Print current and next version
         run: |
-          echo "Current version: ${{ steps.get_semver.outputs.current_version  }}"
+          echo "Current version: ${{ steps.get_semver.outputs.current_version }}"
           echo "Next version: ${{ steps.get_semver.outputs.next_version }}"
+
+      # - name: setup-docker
+      #   uses: docker-practice/actions-setup-docker@master
+      # - name: Download build artifact
+      #   uses: actions/download-artifact@v3
+      #   with:
+      #     name: build
+      #     path: ./dist
+      # - name: Generate version
+      #   run: ./create-version-file.sh
+      # - name: Login to Docker Hub
+      #   uses: docker/login-action@v2
+      #   with:
+      #     username: ${{ secrets.DOCKER_HUB_STAGING_LOGIN }}
+      #     password: ${{ secrets.DOCKER_HUB_STAGING_PASSWORD }}
+      # - name: Build and push image
+      #   run: docker buildx build --platform linux/amd64,linux/arm64 -t orbsnetworkstaging/ethereum-writer:$(cat .version) --push .
+
 
   # release-to-staging:
   #   if: github.event_name == 'pull_request' && github.head_ref == 'main'
